# Generated by Django 5.2 on 2025-04-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='total_sale',
            new_name='total_sales',
        ),
    ]
